export const TEAMS = [
  { id: 'bills', name: 'Bills', initialPsi: 44, coins: 12, ability: 'After the Auction Phase, you may pay the Minimum cost for a player in the discard pile (once per game)' },
  { id: 'dolphins', name: 'Dolphins', initialPsi: 45, coins: 9, ability: 'Whenever you have 0 coins, gain 3' },
  { id: 'patriots', name: 'Patriots', initialPsi: 36, coins: 7, ability: 'Starts with low PSI' },
  { id: 'jets', name: 'Jets', initialPsi: 44, coins: 7, ability: 'Every time you pay the Maximum for a player deflate 4 PSI' },
  { id: 'ravens', name: 'Ravens', initialPsi: 42, coins: 14, ability: 'At the end of the round, if you control 3 different positions in your lineup, gain 3 coins' },
  { id: 'bengals', name: 'Bengals', initialPsi: 46, coins: 9, ability: 'Players with instant abilities give you +2 coins/deflate. When acquiring a player, you may discard them instead of replacing a player.' },
  { id: 'browns', name: 'Browns', initialPsi: 45, coins: 20, ability: 'Players can’t give you coins. Gain 30 coins after round 5' },
  { id: 'steelers', name: 'Steelers', initialPsi: 48, coins: 12, ability: 'At the start of the round, if you are the richest player, give every other player a PSI' },
  { id: 'texans', name: 'Texans', initialPsi: 47, coins: 8, ability: 'During the Refresh Phase gain 2 coins and 2 deflate for each QB on your team' },
  { id: 'colts', name: 'Colts', initialPsi: 50, coins: 5, ability: 'You have unlimited player spots in your lineup. When you acquire a player, add them to your lineup as an additional member.' },
  { id: 'jaguars', name: 'Jaguars', initialPsi: 43, coins: 12, ability: 'You can secretly look at the order of the event deck at any time. Once per game you can rearrange the order of the event deck.' },
  { id: 'titans', name: 'Titans', initialPsi: 44, coins: 7, ability: 'At the beginning of the game, look at the top three cards of the players deck. Acquire one for free. Shuffle the Player Deck' },
  { id: 'broncos', name: 'Broncos', initialPsi: 40, coins: 20, ability: 'The first Refresh Phase after you buy a player, ignore their every turn abilities' },
  { id: 'chiefs', name: 'Chiefs', initialPsi: 46, coins: 9, ability: 'At the start of the Auction Phase you may pay the Minimum cost of a player without bidding (once per game)' },
  { id: 'raiders', name: 'Raiders', initialPsi: 45, coins: 8, ability: 'Before the Auction Phase, you may give 1 PSI you control to another player' },
  { id: 'chargers', name: 'Chargers', initialPsi: 50, coins: 6, ability: 'Each time you outbid a player, gain 1 coin at the end of the round' },
  { id: 'cowboys', name: 'Cowboys', initialPsi: 42, coins: 5, ability: 'Gain 2 coins at the end of every round' },
  { id: 'eagles', name: 'Eagles', initialPsi: 47, coins: 15, ability: 'After the Auction Phase, you may pay 3 coins to raise every other player’s PSI by 3 (Limit twice per round)' },
  { id: 'commanders', name: 'Commanders', initialPsi: 43, coins: 7, ability: 'At the start of the Auction Phase, mark a revealed player. The first player cannot bid on that player.' },
  { id: 'bears', name: 'Bears', initialPsi: 42, coins: 13, ability: 'Players have to outbid you by two coins instead of one' },
  { id: 'lions', name: 'Lions', initialPsi: 47, coins: 9, ability: 'During the Auction Phase, if you are the first player to claim a player, gain coins equal to the number of players' },
  { id: 'packers', name: 'Packers', initialPsi: 50, coins: 8, ability: 'If all your players are Phase 1 players, deflate 4 at the end of the round. Gain 1 coin every time you acquire a Phase 1 player' },
  { id: 'vikings', name: 'Vikings', initialPsi: 44, coins: 11, ability: 'If you have less than 27 PSI, your players receive twice as many coins' },
  { id: 'falcons', name: 'Falcons', initialPsi: 48, coins: 9, ability: 'Whenever starting the bid during Auction, you may swap all available players with new ones (once per phase)' },
  { id: 'saints', name: 'Saints', initialPsi: 42, coins: 12, ability: 'Negative coins and inflation don’t affect you' },
  { id: 'panthers', name: 'Panthers', initialPsi: 49, coins: 10, ability: 'Deflate 2 PSI at the end of every round' },
  { id: 'buccaneers', name: 'Buccaneers', initialPsi: 45, coins: 10, ability: 'After setup, choose another player’s team ability. The Buccaneers gain that ability' },
  { id: 'cardinals', name: 'Cardinals', initialPsi: 41, coins: 15, ability: 'During the Auction Phase, look at top card of Player Deck and swap with one revealed player' },
  { id: 'rams', name: 'Rams', initialPsi: 49, coins: 11, ability: 'Once per game, you may put a x2 token on one of your non-Phase 1 players' },
  { id: '49ers', name: '49ers', initialPsi: 44, coins: 8, ability: 'If you have less than 5 coins during the Refresh Phase, your players generate double deflation.' },
  { id: 'seahawks', name: 'Seahawks', initialPsi: 46, coins: 12, ability: 'Start the game with 4 Practice Squad Players on your team' },
];

export const EVENTS = [
  { id: 'e1', name: 'Offensive Battle', effect: 'Your lineup receives double coins and deflation this round', category: 'double_all' },
  { id: 'e2', name: 'Hot Air', effect: 'Inflate all players’ PSI by 7', category: 'instant_inflate', amount: 7 },
  { id: 'e3', name: 'Cold Air', effect: 'Deflate each player’s PSI by 7', category: 'instant_deflate', amount: 7 },
  { id: 'e4', name: 'Penalty Flag (Coins)', effect: 'Each player can only make a maximum of 10 coins this round', category: 'cap_coins', maxCoins: 10 },
  { id: 'e5', name: 'Penalty Flag (PSI)', effect: 'Each player can only deflate a maximum of 5 PSI this round', category: 'cap_deflate', maxDeflate: 5 },
  { id: 'e6', name: 'Refs Check', effect: 'All Quarterbacks can only deflate PSI or make coins this round (choose for each QB)', category: 'qb_choice' },
  { id: 'e7', name: 'Raw Talent', effect: 'All Phase 1 players receive double coins and deflation this round', category: 'double_phase1' },
  { id: 'e8', name: 'Player Demands a Trade', effect: 'Draw top card of the deck, players may bid before regular bidding phase', category: 'bonus_auction' },
  { id: 'e9', name: 'Free Agency', effect: 'Every player draws top card; may pay max price to swap into lineup', category: 'free_agency' },
  { id: 'e10', name: 'Trade Rumors', effect: 'Everyone picks one active player and passes it to the right', category: 'pass_right' },
  { id: 'e11', name: 'New Cap Limit', effect: 'Each player can pay 10 coins to add a practice squad player', category: 'buy_practice_squad' },
  { id: 'e12', name: 'Rookie Class', effect: 'Draw twice the number of players during Auction Phase', category: 'double_draft' },
  { id: 'e13', name: 'Team Legend Returns', effect: 'Add a random Phase 2 player to the top of the Player Deck (Hall of Fame player instead if it is round 5 or later)', category: 'legend_returns' },
  { id: 'e14', name: '1st Overall Pick', effect: 'Player with highest PSI deflates to match second highest', category: 'match_second_psi' },
  { id: 'e15', name: 'Rivalry', effect: 'Starting with 1st player, each player gives 1 PSI to player of choice', category: 'give_psi' },
  { id: 'e16', name: 'Overpaid', effect: 'Increase the Maximum cost to buy each player by 4', category: 'overpaid', maxAdd: 4 }
];

export const PRACTICE_SQUAD_CARD = {
  id: 'practice_squad',
  name: 'Practice Squad Player',
  position: 'WR',
  minBid: 0,
  maxBid: 0,
  effects: [
    { type: 'coins', amount: 1, perRound: true }
  ]
};

export const PHASE_1_PLAYERS = [
  { id: 'deshaun_watson', name: 'Deshaun Watson', position: 'QB', phase: 1, minBid: 1, maxBid: 5, effects: [{ type: 'inflate', amount: 4, perRound: true }, { type: 'coins', amount: 5, perRound: true }] },
  { id: 'rome_odunze', name: 'Rome Odunze', position: 'WR', phase: 1, minBid: 1, maxBid: 3, effects: [{ type: 'coins', amount: 5, perRound: false }] },
  { id: 'bijan_robinson', name: 'Bijan Robinson', position: 'RB', phase: 1, minBid: 1, maxBid: 6, effects: [{ type: 'deflate', amount: 3, perRound: false }] },
  { id: 'aj_brown', name: 'AJ Brown', position: 'WR', phase: 1, minBid: 1, maxBid: 9, effects: [{ type: 'coins', amount: 3, perRound: true }] },
  { id: 'kirk_cousins', name: 'Kirk Cousins', position: 'QB', phase: 1, minBid: 1, maxBid: 10, effects: [{ type: 'deflate', amount: 4, perRound: true }, { type: 'coins', amount: 1, perRound: true }] },
  { id: 'george_kittle', name: 'George Kittle', position: 'TE', phase: 1, minBid: 1, maxBid: 15, effects: [{ type: 'deflate', amount: 2, perRound: true }, { type: 'deflate', amount: 2, perRound: false }] },
  { id: 'chuba_hubbard', name: 'Chuba Hubbard', position: 'RB', phase: 1, minBid: 1, maxBid: 3, effects: [{ type: 'deflate', amount: 2, perRound: false }] },
  { id: 'dallas_goedert', name: 'Dallas Goedert', position: 'TE', phase: 1, minBid: 1, maxBid: 10, effects: [{ type: 'deflate', amount: 2, perRound: true }] },
  { id: 'juju_smith_schuster', name: 'Juju Smith-Schuster', position: 'WR', phase: 1, minBid: 1, maxBid: 5, effects: [{ type: 'coins', amount: 2, perRound: true }] },
  { id: 'amari_cooper', name: 'Amari Cooper', position: 'WR', phase: 1, minBid: 1, maxBid: 9, effects: [{ type: 'coins', amount: 3, perRound: true }] },
  { id: 'isaiah_pacheco', name: 'Isaiah Pacheco', position: 'RB', phase: 1, minBid: 1, maxBid: 15, specialText: 'When you acquire this player, shuffle the Player Card deck and draw the top card. Acquire that player instead of this one. Discard this card.', customText: 'When you acquire this player, shuffle the Player Card deck and draw the top card. Acquire that player instead of this one. Discard this card.', effects: [] },
  { id: 'brock_bowers', name: 'Brock Bowers', position: 'TE', phase: 1, minBid: 1, maxBid: 15, effects: [{ type: 'deflate', amount: 2, perRound: true }, { type: 'deflate', amount: 2, perRound: false }] },
  { id: 'odell_beckham_jr', name: 'Odell Beckham Jr.', position: 'WR', phase: 1, minBid: 1, maxBid: 10, effects: [{ type: 'coins', amount: 3, perRound: true }] },
  { id: 'devonta_smith', name: 'DeVonta Smith', position: 'WR', phase: 1, minBid: 1, maxBid: 9, effects: [{ type: 'coins', amount: 3, perRound: true }] },
  { id: 'jaylen_waddle', name: 'Jaylen Waddle', position: 'WR', phase: 1, minBid: 1, maxBid: 12, specialText: 'After a player bids on this player, they immediately gain 1 coin.', customText: 'After a player bids on this player, they immediately gain 1 coin.', effects: [{ type: 'coins', amount: 2, perRound: true }] },
  { id: 'zach_ertz', name: 'Zach Ertz', position: 'TE', phase: 1, minBid: 1, maxBid: 10, effects: [{ type: 'deflate', amount: 2, perRound: true }] },
  { id: 'brandon_aiyuk', name: 'Brandon Aiyuk', position: 'WR', phase: 1, minBid: 1, maxBid: 12, specialText: 'If you paid the maximum for this player, 4 coins per round instead.', customText: 'If you paid the maximum for this player, 4 coins per round instead.', effects: [{ type: 'coins', amount: 2, perRound: true }] },
  { id: 'deandre_hopkins', name: 'DeAndre Hopkins', position: 'WR', phase: 1, minBid: 1, maxBid: 9, effects: [{ type: 'coins', amount: 3, perRound: true }] },
  { id: 'sam_laporta', name: 'Sam LaPorta', position: 'TE', phase: 1, minBid: 1, maxBid: 11, effects: [{ type: 'deflate', amount: 2, perRound: true }] },
  { id: 'adam_thielen', name: 'Adam Thielen', position: 'WR', phase: 1, minBid: 1, maxBid: 5, effects: [{ type: 'coins', amount: 2, perRound: true }] },
  { id: 'dalton_schultz', name: 'Dalton Schultz', position: 'TE', phase: 1, minBid: 1, maxBid: 5, effects: [{ type: 'deflate', amount: 1, perRound: true }, { type: 'coins', amount: 1, perRound: false }] },
  { id: 'drake_london', name: 'Drake London', position: 'WR', phase: 1, minBid: 1, maxBid: 14, effects: [{ type: 'coins', amount: 4, perRound: true }] },
  { id: 'kyren_williams', name: 'Kyren Williams', position: 'RB', phase: 1, minBid: 1, maxBid: 8, effects: [{ type: 'deflate', amount: 4, perRound: false }] },
  { id: 'mike_evans', name: 'Mike Evans', position: 'WR', phase: 1, minBid: 1, maxBid: 8, effects: [{ type: 'coins', amount: 3, perRound: true }] },
  { id: 'michael_pittman_jr', name: 'Michael Pittman Jr.', position: 'WR', phase: 1, minBid: 1, maxBid: 10, effects: [{ type: 'coins', amount: 3, perRound: true }] },
  { id: 'tj_hockenson', name: 'TJ Hockenson', position: 'TE', phase: 1, minBid: 1, maxBid: 10, effects: [{ type: 'deflate', amount: 2, perRound: true }] },
  { id: 'xavier_legette', name: 'Xavier Legette', position: 'WR', phase: 1, minBid: 1, maxBid: 2, effects: [{ type: 'coins', amount: 2, perRound: false }] },
  { id: 'josh_allen', name: 'Josh Allen', position: 'QB', phase: 1, minBid: 1, maxBid: 11, effects: [{ type: 'deflate', amount: 2, perRound: true }, { type: 'coins', amount: 4, perRound: false }] },
  { id: 'darren_waller', name: 'Darren Waller', position: 'TE', phase: 1, minBid: 1, maxBid: 11, effects: [{ type: 'deflate', amount: 2, perRound: true }] },
  { id: 'diontae_johnson', name: 'Diontae Johnson', position: 'WR', phase: 1, minBid: 1, maxBid: 8, effects: [{ type: 'coins', amount: 3, perRound: true }] },
  { id: 'tee_higgins', name: 'Tee Higgins', position: 'WR', phase: 1, minBid: 1, maxBid: 15, effects: [{ type: 'coins', amount: 4, perRound: true }] },
  { id: 'michael_thomas', name: 'Michael Thomas', position: 'WR', phase: 1, minBid: 1, maxBid: 5, effects: [{ type: 'coins', amount: 2, perRound: true }] },
  { id: 'greg_olsen', name: 'Greg Olsen', position: 'TE', phase: 1, minBid: 1, maxBid: 14, effects: [{ type: 'deflate', amount: 2, perRound: true }, { type: 'deflate', amount: 2, perRound: false }] },
  { id: 'malik_nabers', name: 'Malik Nabers', position: 'WR', phase: 1, minBid: 1, maxBid: 3, effects: [{ type: 'coins', amount: 5, perRound: false }] },
  { id: 'mark_andrews', name: 'Mark Andrews', position: 'TE', phase: 1, minBid: 1, maxBid: 9, effects: [{ type: 'deflate', amount: 2, perRound: true }] },
  { id: 'hunter_henry', name: 'Hunter Henry', position: 'TE', phase: 1, minBid: 1, maxBid: 12, effects: [{ type: 'deflate', amount: 8, perRound: false }, { type: 'inflate', amount: 3, perRound: true }] },
  { id: 'trevor_lawrence', name: 'Trevor Lawrence', position: 'QB', phase: 1, minBid: 1, maxBid: 15, effects: [{ type: 'inflate', amount: 8, perRound: false }, { type: 'deflate', amount: 3, perRound: true }] },
  { id: 'ezekiel_elliott', name: 'Ezekiel Elliott', position: 'RB', phase: 1, minBid: 1, maxBid: 7, effects: [{ type: 'deflate', amount: 5, perRound: false }, { type: 'coins', amount: -2, perRound: true }] },
  { id: 'devon_achane', name: 'De’Von Achane', position: 'RB', phase: 1, minBid: 1, maxBid: 4, effects: [{ type: 'deflate', amount: 2, perRound: false }] },
  { id: 'kyle_pitts', name: 'Kyle Pitts', position: 'TE', phase: 1, minBid: 1, maxBid: 9, effects: [{ type: 'deflate', amount: 2, perRound: true }] },
  { id: 'jalen_coker', name: 'Jalen Coker', position: 'WR', phase: 1, minBid: 1, maxBid: 5, effects: [{ type: 'coins', amount: 2, perRound: true }] },
  { id: 'dandre_swift', name: 'D’Andre Swift', position: 'RB', phase: 1, minBid: 1, maxBid: 9, effects: [{ type: 'deflate', amount: 4, perRound: false }] },
  { id: 'jayden_daniels', name: 'Jayden Daniels', position: 'QB', phase: 1, minBid: 1, maxBid: 10, effects: [{ type: 'deflate', amount: 3, perRound: false }, { type: 'coins', amount: 2, perRound: true }] },
  { id: 'breece_hall', name: 'Breece Hall', position: 'RB', phase: 1, minBid: 1, maxBid: 5, effects: [{ type: 'deflate', amount: 3, perRound: false }] }
];

export const PHASE_2_PLAYERS = [
  { id: 'kyler_murray', name: 'Kyler Murray', position: 'QB', phase: 2, minBid: 2, maxBid: 13, effects: [{ type: 'deflate', amount: 3, perRound: true }, { type: 'deflate', amount: 1, perRound: false }] },
  { id: 'dj_moore', name: 'DJ Moore', position: 'WR', phase: 2, minBid: 2, maxBid: 10, effects: [{ type: 'deflate', amount: 4, perRound: true }], specialText: 'Only teams with 10 or fewer coins may nominate or bid on DJ Moore.' },
  { id: 'derrick_henry', name: 'Derrick Henry', position: 'RB', phase: 2, minBid: 2, maxBid: 16, effects: [{ type: 'deflate', amount: 4, perRound: true }] },
  { id: 'justin_herbert', name: 'Justin Herbert', position: 'QB', phase: 2, minBid: 2, maxBid: 9, effects: [{ type: 'deflate', amount: 1, perRound: true }, { type: 'deflate', amount: 3, perRound: false }] },
  { id: 'puka_nacua', name: 'Puka Nacua', position: 'WR', phase: 2, minBid: 2, maxBid: 15, effects: [], specialText: 'At start of Refresh Phase, copy an active teammate’s recurring ability this round.' },
  { id: 'dk_metcalf', name: 'DK Metcalf', position: 'WR', phase: 2, minBid: 2, maxBid: 10, effects: [{ type: 'coins', amount: 3, perRound: true }] },
  { id: 'marvin_harrison_jr', name: 'Marvin Harrison Jr.', position: 'WR', phase: 2, minBid: 1, maxBid: 2, effects: [{ type: 'coins', amount: 4, perRound: false }] },
  { id: 'stefon_diggs', name: 'Stefon Diggs', position: 'WR', phase: 2, minBid: 2, maxBid: 13, effects: [{ type: 'coins', amount: 4, perRound: true }] },
  { id: 'garrett_wilson', name: 'Garrett Wilson', position: 'WR', phase: 2, minBid: 2, maxBid: 14, effects: [{ type: 'coins', amount: 4, perRound: true }] },
  { id: 'deebo_samuel', name: 'Deebo Samuel', position: 'WR', phase: 2, minBid: 2, maxBid: 4, effects: [{ type: 'coins', amount: 6, perRound: false }] },
  { id: 'patrick_mahomes', name: 'Patrick Mahomes', position: 'QB', phase: 2, minBid: 2, maxBid: 20, effects: [{ type: 'deflate', amount: 5, perRound: true }, { type: 'coins', amount: 3, perRound: true }] },
  { id: 'brock_purdy', name: 'Brock Purdy', position: 'QB', phase: 2, minBid: 2, maxBid: 15, effects: [{ type: 'deflate', amount: 1, perRound: true }, { type: 'coins', amount: 1, perRound: true }], specialText: 'If among last 2 players acquired this round: gain +5 coins & -3 PSI instantly.' },
  { id: 'joe_burrow', name: 'Joe Burrow', position: 'QB', phase: 2, minBid: 2, maxBid: 17, effects: [{ type: 'deflate', amount: 3, perRound: true }, { type: 'coins', amount: 2, perRound: true }] },
  { id: 'chris_olave', name: 'Chris Olave', position: 'WR', phase: 2, minBid: 1, maxBid: 3, effects: [{ type: 'coins', amount: 5, perRound: false }] },
  { id: 'adrian_peterson', name: 'Adrian Peterson', position: 'RB', phase: 2, minBid: 2, maxBid: 19, effects: [{ type: 'deflate', amount: 5, perRound: true }] },
  { id: 'aaron_jones', name: 'Aaron Jones', position: 'RB', phase: 2, minBid: 2, maxBid: 16, effects: [{ type: 'deflate', amount: 7, perRound: false }] },
  { id: 'davante_adams', name: 'Davante Adams', position: 'WR', phase: 2, minBid: 2, maxBid: 16, effects: [{ type: 'coins', amount: 3, perRound: true }] },
  { id: 'ceedee_lamb', name: 'CeeDee Lamb', position: 'WR', phase: 2, minBid: 2, maxBid: 8, effects: [{ type: 'coins', amount: 5, perRound: true }] },
  { id: 'cooper_kupp', name: 'Cooper Kupp', position: 'WR', phase: 2, minBid: 2, maxBid: 15, effects: [{ type: 'coins', amount: 4, perRound: true }] },
  { id: 'tyreek_hill', name: 'Tyreek Hill', position: 'WR', phase: 2, minBid: 1, maxBid: 12, effects: [{ type: 'deflate', amount: 2, perRound: true }], specialText: 'Whenever any team bids on Tyreek Hill, that team immediately deflates -1 PSI.' },
  { id: 'aaron_rodgers', name: 'Aaron Rodgers', position: 'QB', phase: 2, minBid: 2, maxBid: 10, effects: [{ type: 'deflate', amount: 1, perRound: true }, { type: 'coins', amount: 3, perRound: true }] },
  { id: 'justin_jefferson', name: 'Justin Jefferson', position: 'WR', phase: 2, minBid: 2, maxBid: 19, effects: [{ type: 'coins', amount: 5, perRound: true }] },
  { id: 'tony_pollard', name: 'Tony Pollard', position: 'RB', phase: 2, minBid: 2, maxBid: 7, effects: [{ type: 'deflate', amount: 4, perRound: false }] },
  { id: 'amon_ra_st_brown', name: 'Amon-Ra St. Brown', position: 'WR', phase: 2, minBid: 2, maxBid: 15, effects: [], specialText: 'Steal 1 coin from each opponent at the end of the Refresh Phase.' },
  { id: 'jamarr_chase', name: 'Ja\'Marr Chase', position: 'WR', phase: 2, minBid: 2, maxBid: 18, effects: [{ type: 'coins', amount: 5, perRound: true }] },
  { id: 'jahmyr_gibbs', name: 'Jahmyr Gibbs', position: 'RB', phase: 2, minBid: 2, maxBid: 18, effects: [{ type: 'deflate', amount: 7, perRound: false }] },
  { id: 'jonathan_taylor', name: 'Jonathan Taylor', position: 'RB', phase: 2, minBid: 2, maxBid: 10, effects: [{ type: 'deflate', amount: 3, perRound: true }] },
  { id: 'jalen_hurts', name: 'Jalen Hurts', position: 'QB', phase: 2, minBid: 2, maxBid: 15, effects: [{ type: 'deflate', amount: 2, perRound: true }, { type: 'coins', amount: 2, perRound: true }] },
  { id: 'terry_mclaurin', name: 'Terry McLaurin', position: 'WR', phase: 2, minBid: 2, maxBid: 14, effects: [{ type: 'coins', amount: 4, perRound: true }] },
  { id: 'josh_jacobs', name: 'Josh Jacobs', position: 'RB', phase: 2, minBid: 2, maxBid: 15, effects: [{ type: 'deflate', amount: 3, perRound: true }] },
  { id: 'keenan_allen', name: 'Keenan Allen', position: 'WR', phase: 2, minBid: 1, maxBid: 3, effects: [{ type: 'coins', amount: 5, perRound: false }] },
  { id: 'nick_chubb', name: 'Nick Chubb', position: 'RB', phase: 2, minBid: 2, maxBid: 11, effects: [{ type: 'deflate', amount: 3, perRound: true }] },
  { id: 'chris_godwin', name: 'Chris Godwin', position: 'WR', phase: 2, minBid: 2, maxBid: 8, effects: [{ type: 'deflate', amount: 3, perRound: true }] },
  { id: 'tank_dell', name: 'Tank Dell', position: 'WR', phase: 2, minBid: 2, maxBid: 9, effects: [{ type: 'coins', amount: 3, perRound: true }] },
  { id: 'saquon_barkley', name: 'Saquon Barkley', position: 'RB', phase: 2, minBid: 2, maxBid: 16, effects: [{ type: 'deflate', amount: 4, perRound: true }] },
  { id: 'james_conner', name: 'James Conner', position: 'RB', phase: 2, minBid: 2, maxBid: 12, effects: [{ type: 'deflate', amount: 3, perRound: true }] },
  { id: 'cam_newton', name: 'Cam Newton', position: 'QB', phase: 2, minBid: 2, maxBid: 12, effects: [{ type: 'deflate', amount: 4, perRound: false }, { type: 'coins', amount: 2, perRound: true }] },
  { id: 'russell_wilson', name: 'Russell Wilson', position: 'QB', phase: 2, minBid: 1, maxBid: 6, effects: [{ type: 'deflate', amount: 1, perRound: true }, { type: 'coins', amount: 1, perRound: true }] },
  { id: 'drew_brees', name: 'Drew Brees', position: 'QB', phase: 2, minBid: 2, maxBid: 10, effects: [{ type: 'deflate', amount: 5, perRound: false }, { type: 'coins', amount: 1, perRound: true }] },
  { id: 'lamar_jackson', name: 'Lamar Jackson', position: 'QB', phase: 2, minBid: 2, maxBid: 19, effects: [{ type: 'deflate', amount: 4, perRound: true }, { type: 'coins', amount: 3, perRound: true }] },
  { id: 'dak_prescott', name: 'Dak Prescott', position: 'QB', phase: 2, minBid: 2, maxBid: 15, effects: [{ type: 'deflate', amount: 2, perRound: true }, { type: 'coins', amount: 2, perRound: true }] },
  { id: 'christian_mccaffrey', name: 'Christian McCaffrey', position: 'RB', phase: 2, minBid: 2, maxBid: 17, effects: [{ type: 'deflate', amount: 4, perRound: true }] },
  { id: 'george_pickens', name: 'George Pickens', position: 'WR', phase: 2, minBid: 1, maxBid: 3, effects: [{ type: 'coins', amount: 5, perRound: false }] },
  { id: 'travis_kelce', name: 'Travis Kelce', position: 'TE', phase: 2, minBid: 2, maxBid: 21, effects: [{ type: 'deflate', amount: 6, perRound: true }] },
  { id: 'marshawn_lynch', name: 'Marshawn Lynch', position: 'RB', phase: 2, minBid: 2, maxBid: 20, effects: [{ type: 'deflate', amount: 5, perRound: true }] },
  { id: 'kenneth_walker', name: 'Kenneth Walker', position: 'RB', phase: 2, minBid: 2, maxBid: 14, effects: [{ type: 'deflate', amount: 6, perRound: false }] }
];

export const HOF_PLAYERS = [
  { id: 'calvin_johnson', name: 'Calvin Johnson', position: 'WR', phase: 'hof', minBid: 5, maxBid: 23, effects: [{ type: 'deflate', amount: 7, perRound: true }] },
  { id: 'tony_gonzalez', name: 'Tony Gonzalez', position: 'TE', phase: 'hof', minBid: 5, maxBid: 25, effects: [{ type: 'deflate', amount: 8, perRound: true }] },
  { id: 'peyton_manning', name: 'Peyton Manning', position: 'QB', phase: 'hof', minBid: 5, maxBid: 26, effects: [{ type: 'deflate', amount: 8, perRound: true }] },
  { id: 'jerry_rice', name: 'Jerry Rice', position: 'WR', phase: 'hof', minBid: 5, maxBid: 25, effects: [{ type: 'deflate', amount: 8, perRound: true }] },
  { id: 'brett_favre', name: 'Brett Favre', position: 'QB', phase: 'hof', minBid: 5, maxBid: 28, effects: [{ type: 'deflate', amount: 9, perRound: true }] },
  { id: 'rob_gronkowski', name: 'Rob Gronkowski', position: 'TE', phase: 'hof', minBid: 5, maxBid: 24, effects: [{ type: 'deflate', amount: 7, perRound: true }] },
  { id: 'tom_brady', name: 'Tom Brady', position: 'QB', phase: 'hof', minBid: 5, maxBid: 31, effects: [{ type: 'deflate', amount: 10, perRound: true }] },
  { id: 'joe_montana', name: 'Joe Montana', position: 'QB', phase: 'hof', minBid: 5, maxBid: 27, effects: [{ type: 'deflate', amount: 9, perRound: true }] },
  { id: 'john_elway', name: 'John Elway', position: 'QB', phase: 'hof', minBid: 5, maxBid: 28, effects: [{ type: 'deflate', amount: 9, perRound: true }] },
  { id: 'randy_moss', name: 'Randy Moss', position: 'WR', phase: 'hof', minBid: 5, maxBid: 23, effects: [{ type: 'deflate', amount: 7, perRound: true }] }
];
